# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    container: "maven:3.8-jdk-11"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: mvn --version && mvn -B clean package javadoc:javadoc
